### ISSUE TITLE
Исходники localrunner

### ISSUE THREAD

**Issue by SSS135** [MailRuChamps/raic#1]
Будут ли открыты исходники localrunner?
Лично мне хочется добавить возможность менять состояние мира, хотя бы позицию / скорость ботов

**Comment by Bogotoff** [comment]
Хотелось бы запускать LocalRunner без сокета, и напрямую без задержки передавать команды.
Если исходники это не честно, то как вариант отдельной библиотекой было бы не плохо, чтобы можно было дергать функции, т.е. некий API.

**Comment by mortido** [comment]
> У меня сейчас проблема даже не столько в сокетах, а в том что надо последовательно запрашивать состояния и отдавать команды игроку. Т.е. для двух игроков надо сначала запросить состояние первого, отослать действия первого, запросить второго, отослать второго. Хотелось бы запросить состояние первого и второго, отослать действия первого и второго. Проблема не слишком критичная, но усложняет код.

world содержит состояния всех игроков сразу. Можно посчитать за 1 раз всех, запомнить, а потом просто вовзращать посчитанное.

**Comment by SSS135** [comment]
> > У меня сейчас проблема даже не столько в сокетах, а в том что надо последовательно запрашивать состояния и отдавать команды игроку. Т.е. для двух игроков надо сначала запросить состояние первого, отослать действия первого, запросить второго, отослать второго. Хотелось бы запросить состояние первого и второго, отослать действия первого и второго. Проблема не слишком критичная, но усложняет код.
> 
> world содержит состояния всех игроков сразу. Можно посчитать за 1 раз всех, запомнить, а потом просто вовзращать посчитанное.

Сейчас так и делаю, но надо вносить коррекции для второго игрока, вроде умножения z на -1 и инверсию me / is_teammate. Плюс код взаимодействия с локалранером более запутанный выходит.

**Comment by SannikovDmitry** [comment]
Публиковать сорсцы не будем.
