### ISSUE TITLE
Float and decimal precision selection for calculations

### ISSUE THREAD

**Issue by MelnikovIG** [MailRuChamps/raic#10]
Which one i should use for calculations?  Double or Float? Which one is used on server side?

**Comment by kuviman** [comment]
Server uses 64-bit floats

**Comment by MelnikovIG** [comment]
@kuviman Thanks, so server use https://en.wikipedia.org/wiki/Double-precision_floating-point_format
For Java and C# developers it will be `double` type. Is it correct?

**Comment by kuviman** [comment]
@MelnikovIG Yes
