### ISSUE TITLE
Порядок команд на табло и в игре

### ISSUE THREAD

**Issue by dbf256** [MailRuChamps/raic#11]
![image](https://user-images.githubusercontent.com/2550295/50107350-83deec80-0243-11e9-8d6e-94bf4f122b1c.png)

В игре красные игроки слева, а на табло - красная команда справа. Не критично, но лучше чтобы было одинаково.

**Comment by kuviman** [comment]
Ну, это смотря какой стороны посмотреть :)

Начальное положение камеры теперь совпадает
