### ISSUE TITLE
Why is `ROBOT_MAX_GROUND_SPEED` used to the limit the flightspeed?

### ISSUE THREAD

**Issue by leloykun** [MailRuChamps/raic#123]
I know it's kinda late but wouldn't it be better to use another constant?

**Comment by kuviman** [comment]
What do you mean? `ROBOT_MAX_GROUND_SPEED` is only used for limiting speed on ground, when the robot is not colliding with arena's floor speed is limited by `MAX_ENTITY_SPEED`

**Comment by leloykun** [comment]
OHHH so that's the bug in my strategy

**Comment by leloykun** [comment]
thanks Kuviman!
