### ISSUE TITLE
Дебаг в localrunner

### ISSUE THREAD

**Issue by deniskolsanov** [MailRuChamps/raic#14]
Хотелось бы возможность рисовать отрезки и сферы. А так же выводить логи, но вместе с выводом в консоль на сайте.

**Comment by freeraisor** [comment]
Еще бы неплохо было добавить возможность пошагового исполнения. Каждый шаг вручную запускать с клавиатуры, а не пытаться мышкой попасть в нужный диапазон.

**Comment by ViktorcArmius** [comment]
а еще лучше - не отрезки, а сразу ломаные

**Comment by kuviman** [comment]
> Еще бы неплохо было добавить возможность пошагового исполнения

Потиковое перематывание есть в обновленном раннере

**Comment by kuviman** [comment]
> Хотелось бы возможность рисовать отрезки и сферы

Как вы представляете себе API? Не хочется плодить модели в пакетах

```
MyStrategy::custom_rendering() -> json_string;
```

Библиотеки для работы с json уже подключены. Устроил бы такой вариант?

**Comment by kuviman** [comment]
> с выводом в консоль на сайте
stdout вашей стратегии сейчас можно видеть при клике на иконку языка на странице игры

**Comment by deniskolsanov** [comment]
> MyStrategy::custom_rendering() -> json_string;
Думаю вполне устроит большинство участников.

> stdout вашей стратегии сейчас можно видеть при клике на иконку языка на странице игры
Для отладки в локалраннере нужно выводить информацию каждый тик, и было бы удобно видеть ее в маленьком окошке, или хотя бы текстом поверх изображения. Не удобно искать ошибку перематывая игру и сопоставляя тик с общим логом.
Можно это добавить так же в custom_rendering отдельным полем, просто вывод строки, но чтобы правильно обрабатывались символы переноса строки.

**Comment by mikheevnickita** [comment]
> > Хотелось бы возможность рисовать отрезки и сферы
> 
> Как вы представляете себе API? Не хочется плодить модели в пакетах
> 
Визуальных меток очень не хватает. Очень не хочется пилить свой визуализатор только ради этого.

Самое простое расширить класс Action добавив метки. Сфер должно быть достаточно, отрезки и ломоные не особо нужны. я не думаю что даже тысяча шаров хоть сколько-нибудь заметно скажется на времени отрисовки.
При тестировании и отрисовке статегий эти метки можно просто игнорировать.

```
    class Action
    {
        double target_velocity_x;
        double target_velocity_y;
        double target_velocity_z;
        double jump_speed;
        bool use_nitro;
        Mark[] marks;
    }

    class Mark
    {
        double x;
        double y;
        double z;
        double r;
        ulong rgba;
    }
```

**Comment by kuviman** [comment]
Done
