### ISSUE TITLE
Гравитация

### ISSUE THREAD

**Issue by freeraisor** [MailRuChamps/raic#2]
В правилах и коде не нашел что-либо связанного с гравитацией.
Как падает мяч, как рассчитывается затухание скорости по вертикальной компоненте, если нет никаких касаний с потолком.
Есть ли гравитация? Как она реализована? Или это специально история умалчивает?

**Comment by dbf256** [comment]
@freeraisor в правилах http://russianaicup.ru/s/1545044448241/assets/documentation/codeball2018-docs-ru.pdf?rnd есть упоминание константы GRAVITY, можешь глянуть как она используется.

**Comment by kuviman** [comment]
Гравитация действует по оси `Y` вниз и дает константное ускорение равное `GRAVITY`

[кусок из документации](https://github.com/MailRuChamps/raic/blob/master/docs/ru/Simulation.tex#L40)
