### ISSUE TITLE
Ошибки в формулах документации

### ISSUE THREAD

**Issue by alexeybf** [MailRuChamps/raic#20]
Версия 0.2.2

Вот пример - отсутствует аргумент после запятой в вызовах clamp (таких мест несколько)

стр 12. 
dan = min(dan, dan_to_sphere_inner(
point,
(
clamp(
point.x,
arena.bottom_radius - (arena.goal_width / 2),
(arena.goal_width / 2) - arena.bottom_radius,
),
clamp(
point.y,
arena.bottom_radius,
arena.goal_height - arena.goal_top_radius,
),
(arena.depth / 2) + arena.goal_depth - arena.bottom_radius),
arena.bottom_radius))

**Comment by Flya** [comment]
Похоже это не отсутсвие аргумента, а лишняя запятая.

**Comment by kuviman** [comment]
Лишняя запятая != ошибка в формуле
