### ISSUE TITLE
Игроки не перемещаются

### ISSUE THREAD

**Issue by zamkadisden** [MailRuChamps/raic#23]
В local runner все работает прекрасно.
Загружаю код на сайт - проверку проходит.
Бота ставят в матчи и иногда он играет, а иногда игроки стоят и ничего не делают.
Тоже самое у многих других игроков наблюдается.
Стратегия на С++, но как  говорят на форуме - на других языках та же проблема.

**Comment by kuviman** [comment]
С++, Ruby теперь должны работать.

**Comment by pojmanov** [comment]
К сожалению подобное так и на шарпе. Стратегия http://russianaicup.ru/submission/343/view

**Comment by kuviman** [comment]
@pojmanov Ваша стратегия не работает и в local runner

Проблема в том, что вместо установки полей объекта `action`, вы создаете новый объект, не имеющий отношение к исходному.

**Comment by kuviman** [comment]
Проблем больше быть не должно

**Comment by SitulaAquarius** [comment]
У меня на Java подобное началось. Причем с некоторыми игроками все нормально а с другими алгоритм работать не хочет, боты тупо стоят.

**Comment by SitulaAquarius** [comment]
> Проблем больше быть не должно

У меня на Java подобное началось. Причем с некоторыми игроками все нормально а с другими алгоритм работать не хочет, боты тупо стоят. 
Нормальная игра №20026
Далее игры №20215, №20386 боты стоят
