### ISSUE TITLE
Запуск LocalRunner'а без отрисовки графики (batchmode)

### ISSUE THREAD

**Issue by Bogotoff** [MailRuChamps/raic#24]
Было бы не плохо добавить в аргументы раннера параметр "-batchmode", чтобы раннер запускался без отрисовки и игралось с максимальной скоростью, чтобы быстро можно было запустить и сразу увидеть результат.

**Comment by kuviman** [comment]
Используйте аргумент `--noshow`

**Comment by Bogotoff** [comment]
> 
> 
> Используйте аргумент `--noshow`

То, что надо. Спасибо!
