### ISSUE TITLE
Коллизии между игроками

### ISSUE THREAD

**Issue by freeraisor** [MailRuChamps/raic#3]
Как происходит расчет коллизий между двумя игроками на поле, если они находятся рядом и один из них прыгает(увеличивается в размерах согласно правилам).
Ведь исходя из этой логики игрок НЕ может перепрыгнуть другого игрока. И может даже прыжком, не касаясь, оттолкнуть его.

**Comment by kuviman** [comment]
Они оттолкнут друг друга, [проверьте сами](russianaicup.ru/play)
