### ISSUE TITLE
Verification error

### ISSUE THREAD

**Issue by olsh** [MailRuChamps/raic#31]
When I'm trying to submit a strategy, I get a verification error and empty stdout log
![image](https://user-images.githubusercontent.com/3613592/50183899-85ccac80-0324-11e9-998d-c38f3840c1d2.png)

The strategy works locally without any issues. 
Here is the submission http://russianaicup.ru/submission/607/view

**Comment by Tr1man** [comment]
Та же проблема.  Язык C#, возникает когда в стратегии используется System.Linq.

**Comment by olsh** [comment]
I don't use linq in the strategy.

**Comment by Tr1man** [comment]
В моём случаи ошибка возникает при вызови библиотеки, и исчезает при удалении её из стратегии. Вероятно дело не в самой библиотеки, а в том как на сервере собираются связанные библиотеки. 
![image](https://user-images.githubusercontent.com/13116616/50248366-d78c3a00-03eb-11e9-8682-ab20380af21a.png)

**Comment by vickingur** [comment]
<img width="1300" alt="screen shot 2018-12-20 at 9 49 03 pm" src="https://user-images.githubusercontent.com/156979/50326966-d3225880-04a1-11e9-9082-4cc8e220505c.png">

Та же проблема, никакой информации о причине. Что вообще верифицируется?

**Comment by kuviman** [comment]
This must have been fixed
