### ISSUE TITLE
HTTPS version of website shows old information

### ISSUE THREAD

**Issue by nathan2049** [MailRuChamps/raic#36]
https://russianaicup.ru/ shows information about RAIC 2017.

It is very inconvenient for people using such browser plugins as "HTTPS Everywhere".
Furthermore, google can index https-version and it will be on the top for search query "Russian AI Cup" (threee weeks ago there were no https-version).

**Comment by SannikovDmitry** [comment]
We will fix it soon

**Comment by MelnikovIG** [comment]
Not fully fixed, styles and scripts are not loaded in HTTPS version due they use HTTP version

**Comment by MelnikovIG** [comment]
![image](https://user-images.githubusercontent.com/6163811/50400168-afa72880-0795-11e9-9893-08e39097b5e8.png)
