### ISSUE TITLE
Не определено значение delta_time

### ISSUE THREAD

**Issue by ryzhikovas** [MailRuChamps/raic#4]
Значение переменной delta_time не определено в документации. Кроме того, не сказано, является ли оно вообще константой (если да, его нетрудно вывести, конечно. Но хотелось бы видеть в документации)

**Comment by yanshinalex** [comment]
В правилах на 11 стр. в псевдокоде написано:
let delta_time = 1 / TICKS_PER_SECOND
Среди констант TICKS_PER_SECOND = 60.
Это оно?

**Comment by ryzhikovas** [comment]
> В правилах на 11 стр. в псевдокоде написано:
> let delta_time = 1 / TICKS_PER_SECOND
> Среди констант TICKS_PER_SECOND = 60.
> Это оно?

Да, похоже, спасибо) Не дочитал до этого места...
