### ISSUE TITLE
Tensorflow for Python and Java

### ISSUE THREAD

**Issue by romasffm** [MailRuChamps/raic#43]
It would be very useful to have Tensorflow for Python and Java
Seems not to be that hard to add it.

Please, help the neural nets to get inthere :)

**Comment by romasffm** [comment]
See here also: http://russianaicup.ru/forum/index.php?topic=900.0

**Comment by SannikovDmitry** [comment]
I think that tensorflow isnt good idea because our servers have restrictions.

**Comment by stalkermustang** [comment]
Use torch 
![be man](https://cdn.fishki.net/upload/post/201408/06/1291525/13020936917000.jpg)

**Comment by SannikovDmitry** [comment]
so yeah ^

**Comment by romasffm** [comment]
Does it mean NO?

Or should people have the opportunity just to try and find out, 
if 256 Mb is enough for prediction only, not for training!?
Did you mean this restriction?

So, guys let us try it, if it fails, it was my time spent for nothing, OK?

But there is still a problem with TF 1.12, it requires Python 3.6
Is it a problem to downgrade?
Or just to add 3.6 alongside with 3.7(default)?

**Comment by romasffm** [comment]
Just closed it, very friendly :)
So no chance for TF?
