### ISSUE TITLE
Local runner раз через раз зависает перед тем как начнется игра

### ISSUE THREAD

**Issue by tyamgin** [MailRuChamps/raic#48]
После старта пишет, что уже "client connected", но висит с черным экраном.

Клиент С++17
MacOS

**Comment by kuviman** [comment]
Точно последняя версия пакета?

**Comment by dbf256** [comment]
@kuviman возникла та же проблема под Windows. Сначала было как я описывал в https://github.com/MailRuChamps/raic/issues/19 - т.е. при отладке только проблема с отрисовкой. Вчера обновил локалраннер на свежайший и окно стало именно подвисать.

![image](https://user-images.githubusercontent.com/2550295/50266077-37f29a00-0433-11e9-9307-d1be60f92d50.png)

**Comment by victor-istomin** [comment]
Повторяестя при игре стратегия + empty, после первого вызова MyStrategy::act на версии 0.3.0
![default](https://user-images.githubusercontent.com/6002471/50266344-df6bce80-042b-11e9-99c4-3030ad116ceb.png)

**Comment by kuviman** [comment]
Обновите пакет C++

**Comment by dbf256** [comment]
@kuviman а если пакет java?

**Comment by kuviman** [comment]
@dbf256 Если зависает во время того как вы держите breakpoint, то должно отвиснуть как только вы отпустите, и это другой issue (#19)

**Comment by dbf256** [comment]
Точно, спутал две проблемы. Спасибо, надеюсь теперь на исправление #19

**Comment by victor-istomin** [comment]
> 
> 
> @dbf256 Если зависает во время того как вы держите breakpoint, то должно отвиснуть как только вы отпустите, и это другой issue (#19)

Похоже, зависает после отпускания брекпоинта, причем, со 100% загрузкой ядра

**Comment by tyamgin** [comment]
@kuviman, последняя версия пакета, последняя версия local_runner
проблема повторяется

**Comment by kuviman** [comment]
Попробуйте скачать новую версию раннера (0.3.1)

**Comment by tyamgin** [comment]
Да, исправлено.
