### ISSUE TITLE
Simulation clarification

### ISSUE THREAD

**Issue by mortido** [MailRuChamps/raic#53]
Нужны ли данные куски кода, если есть // Goal back corners где уже (по идее) покрыт кейс всех углов у задней стенки ворот.
https://github.com/MailRuChamps/raic/blob/515f01ae76b4c0ee5f7a712a57215776ae508d95/docs/ru/Simulation.tex#L262

https://github.com/MailRuChamps/raic/blob/515f01ae76b4c0ee5f7a712a57215776ae508d95/docs/ru/Simulation.tex#L296

Похоже, что тут можно просто поставить 0, т.к. мы смотрим толко одну четверть
https://github.com/MailRuChamps/raic/blob/515f01ae76b4c0ee5f7a712a57215776ae508d95/docs/ru/Simulation.tex#L190

На геймдев форуме уже писали, что первый микротик симулируется с прошлым радиусом, а остальные 99 с обновленным https://github.com/MailRuChamps/raic/blob/515f01ae76b4c0ee5f7a712a57215776ae508d95/docs/ru/Simulation.tex#L75

**Comment by kuviman** [comment]
1,2) вроде если убрать эти куски, ничего не поменяется. Но надо ли?)

Про микротики не понял, с чего вы это взяли, радиус используется только при проверке столкновений, которое идет после установки радиуса

**Comment by mortido** [comment]
Можно на 2% быстрее выполнение сделать...

**Comment by kuviman** [comment]
Основная часть времени тратится вашими стратегиями, так что это ни на что не повлияет
