### ISSUE TITLE
Разный random

### ISSUE THREAD

**Issue by Bogotoff** [MailRuChamps/raic#54]
А как сейчас работает рандом и shuffle в псевдокоде симуляции?
Хотелось бы предсказуемый псевдорандом, который не сложно будет реализовать на разных языках.
Достаточно сделать что-то типа такого:
const a = 45;
const c = 21;
const m = 67;
var seed = 2;
const rand = () => seed = (a * seed + c) % m;

**Comment by MelnikovIG** [comment]
Nice joke.
