### ISSUE TITLE
Problems with C++ on server side

### ISSUE THREAD

**Issue by ancientmage** [MailRuChamps/raic#6]
Take C++ empty strategy. Add 2 lines in implementation of function MyStrategy::act
`
action.target_velocity_x = 100;
action.target_velocity_z = 100;
`
Everything works fine on localrunner, but nothing works when push strategy to the server. Robots stay on the spawn locations and look at the ball every tick.
Submit strategy as copy-paste all MyStrategy.cpp file

**Comment by kuviman** [comment]
Should be fixed now

**Comment by ancientmage** [comment]
Thank You. It works for me now (game №1490). 
P.S. The issue can be closed.
