### ISSUE TITLE
Добавить лимит по памяти в JVM

### ISSUE THREAD

**Issue by soon** [MailRuChamps/raic#60]
Сейчас для того чтобы побороть превышение лимита по памяти надо вручную контролировать занимаемый объем и дергать gc когда памяти недостаточно.

Пример посылок: [1492](http://russianaicup.ru/submission/1492/view) (падает) и [1501](http://russianaicup.ru/submission/1501/view) (работает), разница только в `System.gc()`

Вероятно проблема в том, что нет лимита для JVM, предложение добавить `-Xmx250m` в строку запуска `java` для пакетов java и kotlin. Локальные тесты показывают что это лучше чем дергать `System.gc()` руками.

**Comment by dbf256** [comment]
Проблему надо решать, но непонятно по какому принципу убивается jvm-процесс на сервере. Сначала я подумал, что можно дать Xmx=256m, но это же только куча, доступная пользорвателю, а есть еще и память для внутренних структур jvm. 
@kuviman, может просто выделить всем jvm-программам (java/scala/kotlin) 256 мегов в куче и не рушить процесс через OOM? Или если кажется, что это не честно, тогда можно выдать с небольшим запасом (например, 250, как предлагает @soon)? В теории тогда все равно может упасть до срабатывания GC, но шансов будет заметно меньше. Сейчас это по умолчанию ставится в 1GB или 1/4 RAM, что может быть сильно боьше 256 мегов, так что надо править. Вызывать GC вручную не вариант, потому что это будет FullGC и будет занимать значительно больше времени, чем автоматический GC.

**Comment by kuviman** [comment]
Добавлено
