### ISSUE TITLE
Программы для x86-32

### ISSUE THREAD

**Issue by ScaryScarlet** [MailRuChamps/raic#65]
Сделайте, чтобы программы запускались на Windows 32-bit.
Неужели так принципиально для перемещения сфер в параллелепипеде или трансляции координат в стратегию собирать программу в 64-bit?

**Comment by kuviman** [comment]
Здравствуйте. [Попробуйте](http://russianaicup.ru/s/1545569875721/assets/local-runner/codeball2018-windows-x32.zip)

**Comment by ScaryScarlet** [comment]
Спасибо, работает!
