### ISSUE TITLE
How to compile Local Runner in windows computer

### ISSUE THREAD

**Issue by Xlider** [MailRuChamps/raic#78]
I have code in c++

**Comment by kuviman** [comment]
What do you mean? Local runner is already in binary form

Do you mean compile your strategy? In this case, there are Visual Studio project files for example.

**Comment by Xlider** [comment]
Ohh...
Thanks
But how to open project(strategy) and compile in Visual Studio?

**Comment by kuviman** [comment]
You should be able to open `cpp-cgdk.sln` with visual studio, then compile and run from there
