### ISSUE TITLE
Отсутствие css на сайте по https

### ISSUE THREAD

**Issue by Ky3He4iK** [MailRuChamps/raic#88]
https://russianaicup.ru/ - выглядит мягко говоря не очень привлекательно. Скорее всего стили не подгружаются
![screenshot_2018-12-26_12 10 40_ 05](https://user-images.githubusercontent.com/29950337/50436368-6c6cc700-0907-11e9-9e4c-c61e9d349d4f.png)

**Comment by kuviman** [comment]
Fixed
