### ISSUE TITLE
Опечатка в документации? Или Баг в физическом движке!

### ISSUE THREAD

**Issue by tonykozlovsky** [MailRuChamps/raic#90]
### Неправильный рассчёт столкновения роботов при расширении.
Опытным путём в локал раннере проверить возможную ошибку не удалось, из-за сложности воспроизведения.
` let delta_velocity = dot(b.velocity - a.velocity, normal) + b.radius_change_speed - a.radius_change_speed
`
Надо заменить на
`let delta_velocity = dot(b.velocity - a.velocity, normal) - b.radius_change_speed - a.radius_change_speed`
Потому что в случае, когда 2 робота одновременно "расширяются",  вместо того, чтобы оттолкнуться с большей силой, они компенсируют расширение друг друга и вовсе не отталкиваются

**Comment by ivan-kudziev** [comment]
может так и задумано... если один толкает то второй отлетает, если толкают оба то гасят свои силы

**Comment by mixei4** [comment]
Кажется, ошибка воспроизводится с клавиатуры. Если подойти вплотную к стоящему игроку и прыгнуть, то иногда робот отпрыгивает в сторону (робот a), а иногда вертикально вверх (робот b).

**Comment by tonykozlovsky** [comment]
Суть в том, что оба должны прыгнуть одновременно, и чтобы `b.radius_change_speed` было равно `a.radius_change_speed`, по этому я пока не понял, как ты предлагаешь воспроизвести

**Comment by mixei4** [comment]
Я более простой случай рассматриваю. Если расширяется только один робот. Так вот в случае если этот робот по воле случая окажется роботом a, то слолкновение произойдёт, а если b, то нет.

**Comment by kuviman** [comment]
Вы правы, это был баг (не только в документации). Обновлены правила/ЛР
