### ISSUE TITLE
Недоступна константа в C++

### ISSUE THREAD

**Issue by abzalovim** [MailRuChamps/raic#98]
Попробовал отослать свою стратегию. Получил ошибку компиляции на сервере:
./MyStrategy.cpp:23:27: error: 'ROBOT_RADIUS' was not declared in this scope
     double lr=BALL_RADIUS-ROBOT_RADIUS;
./MyStrategy.cpp:23:27: note: suggested alternative: 'ROBOT_MAX_RADIUS'
     double lr=BALL_RADIUS-ROBOT_RADIUS;

Вроде бы в документации везде эта константа указана.
Константу ROBOT_MAX_RADIUS - компилятор увидел, значит константы подтянулись. Но куда делось ROBOT_RADIUS ?

**Comment by neurocore** [comment]
Так они же в объекте Rules передаются при каждом вызове MyStrategy::act

**Comment by abzalovim** [comment]
> 
> 
> Так они же в объекте Rules передаются при каждом вызове MyStrategy::act

Вот именно! И локально все нормально компилируется. Но, почему-то, **на сервере** при отсылке попытки у меня выдало ошибку компиляции.

**Comment by neurocore** [comment]
А где вы считаете это
`double lr=BALL_RADIUS-ROBOT_RADIUS;`
не нужно ли указывать `rules.BALL_RADIUS` и `rules.ROBOT_RADIUS`?

**Comment by abzalovim** [comment]
Вы совершенно правы!
Я взял тестовый пример отсюда: https://github.com/MailRuChamps/raic/blob/master/QUICKSTARTS/%D1%81%2B%2B/StarterC%2B%2B.cpp
А там, оказывается, эти константы в *.h прописаны. Через rules подключаются константы правильно. Спасибо!
